(function () {
  'use strict';
  const results = document.getElementById('lab-results'); if (!results) return;
  const search = document.getElementById('lab-search'), count = document.getElementById('lab-count'), more = document.getElementById('lab-more'), empty = document.getElementById('lab-empty'), clear = document.getElementById('lab-clear');
  const esc = (v) => String(v || '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c])); const size = 10; let labs = [], visible = size;
  const nameAr = { 'Laboratoire Maghreb Arabi': 'مختبر المغرب العربي', 'Laboratoire Nader': 'مختبر نادر', 'Laboratoire Le Vallon': 'مختبر الوادي', 'Laboratoire La Province': 'مختبر الإقليم', 'Laboratoire Al Andalousse': 'مختبر الأندلس', 'Laboratoire Saada': 'مختبر السعادة', 'Laboratoire Asseha': 'مختبر الصحة', 'Laboratoire Biranzarane': 'مختبر ابن زهر', 'Centre de Biologie Médicale Sebou — CBMS': 'مركز سبو للبيولوجيا الطبية', 'Laboratoire Ibn Sina': 'مختبر ابن سينا' };
  function card(p) { const phone = p.phone || (Array.isArray(p.phones) && p.phones[0] && (p.phones[0].number || p.phones[0].label)); const map = p.mapsUrl || p.google_maps_url; return '<article class="lab-card"><div class="lab-card-top"><span class="lab-avatar">✚</span><div><p class="lab-type">مختبر طبي</p><h3>' + esc(nameAr[p.name] || p.nameAr || p.nameEn || p.name) + '</h3></div></div>' + (p.address ? '<p class="lab-detail"><strong>العنوان</strong>' + esc(p.address) + '</p>' : '') + (phone ? '<p class="lab-detail"><strong>الهاتف</strong>' + esc(phone) + '</p>' : '') + '<div class="lab-actions">' + (p.slug ? '<a class="lab-profile" href="laboratoire.html?slug=' + encodeURIComponent(p.slug) + '">عرض الملف</a>' : '') + (phone ? '<a href="tel:' + esc(phone) + '">اتصال</a>' : '') + (map ? '<a href="' + esc(map) + '" target="_blank" rel="noopener">الاتجاهات</a><a href="' + esc(map) + '" target="_blank" rel="noopener">آراء Google</a>' : '') + '</div></article>'; }
  function render() { const q = (search.value || '').trim().toLowerCase(); const list = labs.filter((p) => !q || [p.name,p.nameAr,p.nameEn,p.address,p.district,p.city].filter(Boolean).join(' ').toLowerCase().includes(q)); results.innerHTML = list.slice(0, visible).map(card).join(''); count.textContent = list.length + ' ' + (list.length === 1 ? 'مختبر' : 'مختبرات'); more.hidden = list.length <= visible; empty.hidden = list.length !== 0; }
  fetch('../data/virtual-card-index.json').then((r) => r.json()).then((data) => { labs = data.filter((p) => p.type === 'laboratory' && p.indexable !== false); render(); }).catch(() => { count.textContent = 'تعذر تحميل الدليل'; });
  search.addEventListener('input', () => { visible = size; render(); }); more.addEventListener('click', () => { visible += size; render(); }); clear.addEventListener('click', () => { search.value = ''; visible = size; render(); });
  const toggle = document.querySelector('.menu-toggle'), menu = document.getElementById('labs-menu'); if (toggle && menu) toggle.addEventListener('click', () => { const open = toggle.getAttribute('aria-expanded') === 'true'; toggle.setAttribute('aria-expanded', String(!open)); menu.classList.toggle('is-open', !open); });
}());
