(function () {
  'use strict';
  const results = document.getElementById('clinic-results'); if (!results) return;
  const search = document.getElementById('clinic-search'), type = document.getElementById('clinic-type'), zone = document.getElementById('clinic-zone'), count = document.getElementById('clinic-count'), more = document.getElementById('clinic-more'), empty = document.getElementById('clinic-empty'), clear = document.getElementById('clinic-clear');
  const esc = (v) => String(v || '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c])); const size = 10; let entries = [], visible = size;
  const nameAr = { 'Clinique Internationale de Kénitra': 'المصحة الدولية بالقنيطرة', 'Centre Hospitalier Provincial El-Azemmouri': 'المركز الاستشفائي الإقليمي العزعموري', 'Akdital International Hospital - Kenitra': 'مستشفى أكديطال الدولي بالقنيطرة', 'Polyclinique de Kénitra': 'المصحة متعددة التخصصات بالقنيطرة', 'Polyclinique du Gharb': 'مصحة الغرب', 'Noor Clinic': 'مصحة النور', 'Clinique Val Fleury': 'مصحة فال فلوري', 'Mimosas Clinic': 'مصحة الميموزا', 'Clinique Anoual': 'مصحة أنوال', 'Clinique Sebou': 'مصحة سبو' };
  function card(p) { const phone = p.phone || (Array.isArray(p.phones) && p.phones[0] && (p.phones[0].number || p.phones[0].label)); const map = p.mapsUrl || p.google_maps_url; const label = p.type === 'hospital' ? 'مستشفى' : 'عيادة'; const title = nameAr[p.name] || p.nameAr || p.nameEn || p.name; const subtitleAr = p.subtitle === 'Hôpital privé' ? 'مستشفى خاص' : p.subtitle === 'Hôpital public' ? 'مستشفى عمومي' : p.subtitle === 'Centre chirurgical' ? 'مركز جراحي' : p.subtitle === 'Clinique spécialisée' ? 'مصحة متخصصة' : 'مؤسسة صحية في القنيطرة'; return '<article class="clinic-card"><div class="clinic-card-top"><span class="clinic-avatar">✚</span><div><p class="clinic-type">' + label + '</p><h3>' + esc(title) + '</h3></div></div><p class="clinic-subtitle">' + subtitleAr + '</p>' + (p.address ? '<p class="clinic-location"><strong>العنوان</strong>' + esc(p.address) + '</p>' : '') + (phone ? '<p class="clinic-phone"><strong>الهاتف</strong>' + esc(phone) + '</p>' : '') + '<div class="clinic-actions">' + (p.slug ? '<a class="clinic-profile" href="etablissement.html?slug=' + encodeURIComponent(p.slug) + '">عرض الملف</a>' : '') + (phone ? '<a href="tel:' + esc(phone) + '">اتصال</a>' : '') + (map ? '<a href="' + esc(map) + '" target="_blank" rel="noopener">الاتجاهات</a><a href="' + esc(map) + '" target="_blank" rel="noopener">آراء Google</a>' : '') + '</div></article>'; }
  function render() { const q = (search.value || '').trim().toLowerCase(); const list = entries.filter((p) => (!q || [p.name,p.nameAr,p.nameEn,p.subtitle,p.address,p.district,p.city].filter(Boolean).join(' ').toLowerCase().includes(q)) && (!type.value || p.type === type.value) && (!zone.value || (p.district || p.zone) === zone.value)); results.innerHTML = list.slice(0, visible).map(card).join(''); count.textContent = list.length + ' ' + (list.length === 1 ? 'مؤسسة' : 'مؤسسات'); more.hidden = list.length <= visible; empty.hidden = list.length !== 0; }
  fetch('../../data/virtual-card-index.json').then((r) => r.json()).then((data) => { entries = data.filter((p) => (p.type === 'clinic' || p.type === 'hospital') && p.indexable !== false); [...new Set(entries.map((p) => p.district || p.zone).filter(Boolean))].sort().forEach((v) => zone.insertAdjacentHTML('beforeend', '<option value="' + esc(v) + '">' + esc(v) + '</option>')); type.insertAdjacentHTML('beforeend', '<option value="clinic">عيادة</option><option value="hospital">مستشفى</option>'); render(); }).catch(() => { count.textContent = 'تعذر تحميل الدليل'; });
  [search,type,zone].forEach((el) => el.addEventListener(el === search ? 'input' : 'change', () => { visible = size; render(); })); more.addEventListener('click', () => { visible += size; render(); }); clear.addEventListener('click', () => { search.value = ''; type.value = ''; zone.value = ''; visible = size; render(); });
  const toggle = document.querySelector('.menu-toggle'), menu = document.getElementById('clinics-menu'); if (toggle && menu) toggle.addEventListener('click', () => { const open = toggle.getAttribute('aria-expanded') === 'true'; toggle.setAttribute('aria-expanded', String(!open)); menu.classList.toggle('is-open', !open); });
}());
