(function () {
  'use strict';
  const results = document.getElementById('dialysis-results'); if (!results) return;
  const search = document.getElementById('dialysis-search'), zone = document.getElementById('dialysis-zone'), count = document.getElementById('dialysis-count'), more = document.getElementById('dialysis-more'), empty = document.getElementById('dialysis-empty'), clear = document.getElementById('dialysis-clear');
  const esc = (v) => String(v || '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c])); const size = 8; let centers = [], visible = size;
  function card(c) { const phone = Array.isArray(c.phones) && c.phones[0]; const map = c.google_maps_url || (c.address ? 'https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent((c.address || '') + (c.city ? ', ' + c.city : '')) : ''); return '<article class="dialysis-card"><div class="dialysis-card-top"><span class="dialysis-avatar">⌁</span><div><p class="dialysis-type">مركز تصفية الدم</p><h3>' + esc(c.name) + '</h3></div></div>' + (c.sector ? '<p class="dialysis-detail"><strong>القطاع</strong>' + esc(c.sector) + '</p>' : '') + (c.city ? '<p class="dialysis-detail"><strong>المدينة</strong>' + esc(c.city) + '</p>' : '') + (c.address ? '<p class="dialysis-detail"><strong>العنوان</strong>' + esc(c.address) + '</p>' : '') + (c.specialty ? '<p class="dialysis-detail"><strong>التخصص</strong>' + esc(c.specialty) + '</p>' : '') + '<div class="dialysis-actions">' + (c.id ? '<a class="dialysis-profile" href="centre-dialyse.html?id=' + encodeURIComponent(c.id) + '">عرض الملف</a>' : '') + (phone ? '<a href="tel:' + esc(phone) + '">اتصال</a>' : '') + (map ? '<a href="' + esc(map) + '" target="_blank" rel="noopener">الاتجاهات</a><a href="' + esc(map) + '" target="_blank" rel="noopener">آراء Google</a>' : '') + '</div></article>'; }
  function render() { const q = (search.value || '').trim().toLowerCase(), selected = zone.value; const list = centers.filter((c) => (!q || [c.name,c.sector,c.address,c.city,c.specialty,c.doctor_responsible].filter(Boolean).join(' ').toLowerCase().includes(q)) && (!selected || c.sector === selected)); results.innerHTML = list.slice(0, visible).map(card).join(''); count.textContent = list.length + ' ' + (list.length === 1 ? 'مركز' : 'مراكز'); empty.hidden = list.length !== 0; more.hidden = list.length <= visible; }
  fetch('../../data/dialysis-centers.json').then((r) => r.json()).then((data) => { centers = data.centers || []; [...new Set(centers.map((c) => c.sector).filter(Boolean))].sort().forEach((v) => zone.insertAdjacentHTML('beforeend', '<option value="' + esc(v) + '">' + esc(v) + '</option>')); render(); }).catch(() => { count.textContent = 'تعذر تحميل الدليل'; });
  search.addEventListener('input', () => { visible = size; render(); }); zone.addEventListener('change', () => { visible = size; render(); }); more.addEventListener('click', () => { visible += size; render(); }); clear.addEventListener('click', () => { search.value = ''; zone.value = ''; visible = size; render(); });
  const toggle = document.querySelector('.menu-toggle'), menu = document.getElementById('dialysis-menu'); if (toggle && menu) toggle.addEventListener('click', () => { const open = toggle.getAttribute('aria-expanded') === 'true'; toggle.setAttribute('aria-expanded', String(!open)); menu.classList.toggle('is-open', !open); });
}());
