(function () {
  'use strict';
  const results = document.getElementById('duty-results'), meta = document.getElementById('duty-meta'), status = document.getElementById('duty-status'); if (!results) return;
  const esc = (v) => String(v || '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  Promise.all([fetch('../../data/pharmacies-garde-2026-09-28-10-02.json').then((r) => r.json()), fetch('../../data/pharmacies-kenitra.json').then((r) => r.json()).catch(() => ({ pharmacies: [] }))]).then(([data, directory]) => {
    meta.textContent = data.displayDateAr || 'آخر تحديث متاح';
    const groups = [['day', 'الحراسة النهارية'], ['night', 'الحراسة الليلية']].flatMap(([key, label]) => (data.duty && data.duty[key] || []).map((p) => ({ ...p, periodLabel: label })));
    status.textContent = groups.length + ' صيدليات مناوبة';
    const list = directory.pharmacies || [];
    if (!groups.length) { results.innerHTML = '<div class="pharmacy-empty"><strong>لا تتوفر معلومات صيدليات الحراسة لهذه الفترة.</strong><a href="pharmacies.html">عرض جميع الصيدليات</a></div>'; return; }
    results.innerHTML = groups.map((p) => { const permanent = list.find((x) => x.id === p.directoryId || x.id === p.id); const phone = p.phone || permanent && permanent.phone; const map = p.mapsUrl || p.google_maps_url || permanent && (permanent.mapsUrl || permanent.google_maps_url); const profile = permanent && permanent.slug ? '<a href="pharmacie.html?slug=' + encodeURIComponent(permanent.slug) + '">عرض الملف</a>' : ''; return '<article class="duty-card"><div class="duty-card-head"><span>' + esc(p.periodLabel) + '</span><b>مناوبة</b></div><h3>' + esc(p.nameAr || p.name || permanent && permanent.name) + '</h3>' + (p.hoursAr ? '<p class="duty-hours">' + esc(p.hoursAr) + '</p>' : '') + (p.districtAr || p.district || permanent && permanent.district ? '<p><strong>الحي</strong>' + esc(p.districtAr || p.district || permanent && permanent.district) + '</p>' : '') + (p.addressAr || p.address || permanent && permanent.address ? '<p><strong>العنوان</strong>' + esc(p.addressAr || p.address || permanent && permanent.address) + '</p>' : '') + (phone ? '<p><strong>الهاتف</strong>' + esc(phone) + '</p>' : '') + '<div class="duty-actions">' + (phone ? '<a href="tel:' + esc(phone) + '">اتصال</a>' : '') + (map ? '<a href="' + esc(map) + '" target="_blank" rel="noopener">الاتجاهات</a>' : '') + profile + '</div></article>'; }).join('');
  }).catch(() => { status.textContent = 'تعذر تحميل معلومات الحراسة'; results.innerHTML = '<div class="pharmacy-empty"><strong>معلومات الحراسة غير متاحة حالياً.</strong><a href="pharmacies.html">عرض جميع الصيدليات</a></div>'; });
  const toggle = document.querySelector('.menu-toggle'), menu = document.getElementById('duty-menu'); if (toggle && menu) toggle.addEventListener('click', () => { const open = toggle.getAttribute('aria-expanded') === 'true'; toggle.setAttribute('aria-expanded', String(!open)); menu.classList.toggle('is-open', !open); });
}());
