(function () {
  'use strict';
  const root = document.getElementById('specialty-results'); if (!root) return;
  const chips = document.getElementById('specialty-chips'), count = document.getElementById('specialty-count'); let doctors = [];
  const esc = (v) => String(v || '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const ar = { Cardiologue: 'أمراض القلب', Neurologue: 'طب الأعصاب', Pédiatre: 'طب الأطفال', Gynécologue: 'أمراض النساء والتوليد', Dermatologue: 'الأمراض الجلدية', Ophtalmologue: 'طب العيون', Urologue: 'المسالك البولية', Pneumologue: 'أمراض الصدر', Rhumatologue: 'أمراض المفاصل', Endocrinologue: 'الغدد والسكري', 'Gastro-entérologue': 'أمراض الجهاز الهضمي', ORL: 'الأنف والأذن والحنجرة' };
  function card(d) { const phone = d.phones && d.phones[0] && (d.phones[0].number || d.phones[0].label); return '<article class="specialty-card"><span class="specialty-number">' + esc(ar[d.subtitle] || 'تخصص طبي') + '</span><h3>' + esc(d.name) + '</h3><p>' + esc(d.subtitle || 'طبيب') + ' · ' + esc(d.city || 'القنيطرة') + '</p><div>' + (phone ? '<a href="tel:' + esc(phone) + '">اتصال</a>' : '') + '<a href="medecin.html?slug=' + encodeURIComponent(d.slug || '') + '">عرض الملف</a></div></article>'; }
  function render(value) { const list = doctors.filter((d) => !value || d.subtitle === value); root.innerHTML = list.slice(0, 30).map(card).join(''); count.textContent = list.length + ' ' + (list.length === 1 ? 'طبيب' : 'أطباء'); }
  fetch('/data/virtual-card-index.json').then((r) => r.json()).then((data) => { doctors = data.filter((d) => d.type === 'doctor' && d.indexable !== false); const values = [...new Set(doctors.map((d) => d.subtitle).filter(Boolean))]; chips.innerHTML = '<button type="button" data-value="">جميع التخصصات</button>' + values.map((v) => '<button type="button" data-value="' + esc(v) + '">' + esc(ar[v] || v) + '</button>').join(''); chips.addEventListener('click', (e) => { const button = e.target.closest('button'); if (button) render(button.dataset.value); }); render(''); }).catch(() => { root.innerHTML = '<p>تعذر تحميل التخصصات حالياً.</p>'; });
  const toggle = document.querySelector('.menu-toggle'), menu = document.getElementById('specialty-menu'); if (toggle && menu) toggle.addEventListener('click', () => { const open = toggle.getAttribute('aria-expanded') === 'true'; toggle.setAttribute('aria-expanded', String(!open)); menu.classList.toggle('is-open', !open); });
}());
