(() => {
  const article = document.querySelector('.rose-article-card'); if (!article) return;
  const hero = article.querySelector('.rose-article-hero');
  const author = article.querySelector('.rose-author');
  if (hero) { const share = document.createElement('div'); share.className = 'article-stats rose-share-bar'; share.innerHTML = '<button type="button" class="article-share-button">□ Partager</button><span class="article-share-status" role="status" aria-live="polite"></span>'; share.querySelector('button').addEventListener('click', async () => { const status = share.querySelector('.article-share-status'); try { if (navigator.share) await navigator.share({title: document.title, url: location.href}); else { await navigator.clipboard.writeText(location.href); status.textContent = 'Lien copié'; } } catch (error) { if (error.name !== 'AbortError') status.textContent = 'Copie du lien indisponible'; } }); hero.after(share); }
  if (author) { const controls = document.createElement('div'); controls.className = 'article-reading-controls rose-reading-controls'; controls.innerHTML = '<span>LECTURE</span><button type="button" data-reading="smaller" aria-label="Réduire la taille du texte">A−</button><button type="button" data-reading="larger" aria-label="Augmenter la taille du texte">A+</button><button type="button" data-reading="comfort" aria-pressed="false">Mode confortable</button>'; author.before(controls); controls.addEventListener('click', (event) => { const button = event.target.closest('button'); if (!button) return; if (button.dataset.reading === 'smaller') document.body.classList.add('reading-small'); if (button.dataset.reading === 'larger') document.body.classList.remove('reading-small'); if (button.dataset.reading === 'comfort') { document.body.classList.toggle('reading-comfort'); button.setAttribute('aria-pressed', document.body.classList.contains('reading-comfort')); } }); }
  const follow = document.createElement('section'); follow.className = 'article-follow-up rose-follow-up'; follow.innerHTML = '<div><span class="article-follow-up__eyebrow">BESOIN D’ACCOMPAGNEMENT ?</span><h2>Une question sur votre santé ?</h2><p>Medomicile vous oriente vers la solution adaptée à Kénitra.</p></div><a href="../contact.html">Contacter Medomicile →</a>'; article.after(follow);
  const related = document.createElement('section'); related.className = 'article-related rose-related'; related.innerHTML = '<span class="article-follow-up__eyebrow">À LIRE AUSSI</span><div><a class="related-card related-card--burns" href="brulures-premiers-gestes.html"><span>PREMIERS SECOURS</span><strong>Les premiers gestes face aux brûlures</strong><small>Les réflexes essentiels à connaître à la maison.</small><b>Lire l’article →</b></a><a class="related-card related-card--antibiotics" href="antibiotiques-infections-bon-usage.html"><span>BON USAGE DES MÉDICAMENTS</span><strong>Bien utiliser les antibiotiques</strong><small>Comprendre quand ils sont utiles et pourquoi.</small><b>Lire l’article →</b></a><a class="related-card related-card--hypoglycemia" href="hypoglycemie-reconnaitre-signes-agir.html"><span>PRÉVENTION</span><strong>Reconnaître une hypoglycémie</strong><small>Les signes et les bons réflexes à adopter.</small><b>Lire l’article →</b></a></div>';
  follow.after(related);
  const footer = document.querySelector('.site-footer'); if (footer) footer.innerHTML = '<div class="footer-grid"><div><strong>Medomicile</strong><p>Consultations, soins et orientation à Kénitra.</p></div><div><b>Services</b><a href="../consultation.html">Consultation à domicile</a><a href="../ambulance.html">Ambulance</a><a href="../urgences.html">Urgences</a></div><div><b>Annuaire</b><a href="../medecins.html">Médecins</a><a href="../pharmacies.html">Pharmacies</a><a href="../cliniques.html">Cliniques / Hôpitaux</a><a href="../laboratoires.html">Laboratoires</a><a href="../radiologie.html">Radiologie</a><a href="../dialyse.html">Dialyse</a></div><div><b>Informations</b><a href="../articles.html">Articles</a><a href="../contact.html">Contact</a><a href="../confidentialite.html">Confidentialité</a></div><div><b>Langues</b><a href="../ar/index.html">العربية</a><a href="../index.html">Français</a><a href="../en/index.html">English</a></div></div>';
})();
